# Generated by Django 5.2 on 2025-05-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('waste_level', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Empty', 'Empty'), ('Half', 'Half'), ('Full', 'Full')], max_length=10)),
            ],
        ),
    ]
